### PR TITLE
Add Rarest/Sequential toggle to torrents

### PR DESCRIPTION
**Pull request by Luminarys**

### CODE REVIEW

**Comment by SirCmpwn** [comment]
If synapse doesn't represent it as an enum neither should we. Checkbox would be better.

**Comment by Luminarys** [comment]
Fair point

**Comment by Luminarys** [comment]
Changed to check box, though it looks a bit odd now alongside the other input types

**Comment by SirCmpwn** [comment]
Screenshot? You could also add an enum to synapse

**Comment by Luminarys** [comment]
https://sr.ht/SDvH.png

I'm not sure about changing it to an enum since I don't anticipate there being other strategies used, though if that does end up being the case I will change it.

**Comment by SirCmpwn** [comment]
I would give it a label ("Download strategy") or something.

Also you can never change it because backwards compatability so pick a choice you can be happy with forever.

**Comment by Luminarys** [comment]
I'll think about it some more then.

**Comment by Luminarys** [comment]
I've reverted back to the old input selection and changed the sequential field from a boolean to a strategy enum to better reflect the intent in RPC.

**Comment by SirCmpwn** [comment]
>I would give it a label ("Download strategy") or something.

**Comment by Luminarys** [comment]
Fixed

**Comment by SirCmpwn** [comment]
Wait so are you doing the enum thing on the synapse side then

**Comment by Luminarys** [comment]
Yep

**Pull request merged**
