### PR TITLE
Improve throttle UX

### PR DESCRIPTION
**Pull request by Luminarys**
Allows backspacing in throttle and memory of previous value

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This only looks like half of the remember work?

**Comment by Luminarys** [comment]
How so?

**Comment by SirCmpwn** [comment]
Oh, I see what you're going for here. Can you name the `prevLimit` thing `custom` instead?

**Comment by Luminarys** [comment]
sure

**Comment by SirCmpwn** [comment]
tyvm

**Pull request merged**
